name: Detecting Unwanted Cypress Modifiers

on:
  pull_request:
    paths:
      - '**/*.cy.js'
      - '**/cypress/**'

jobs:
  cypress-modifiers-check:
    runs-on: ubuntu-latest
    name: Check for `.skip` and `.only` in Cypress code
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files: |
            **/*.cy.js
            **/cypress/**

      - name: Check for .skip and .only in Cypress files
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          echo "Checking Cypress files for .skip and .only..."
          echo "Changed files: ${{ steps.changed-files.outputs.all_changed_files }}"
          
          # Initialize flag
          MODIFIERS_FOUND=false
          
          # Check each changed file
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [[ -f "$file" ]]; then
              echo "Checking file: $file"
              
              # Check for .skip with line numbers (exclude this.skip() and commented lines)
              SKIP_RESULTS=$(grep -n "\.skip" "$file" | grep -v "this\.skip" | grep -v "^\s*//" || true)
              if [[ -n "$SKIP_RESULTS" ]]; then
                echo -e "\n⚠️ Found .skip in $file:"
                echo "$SKIP_RESULTS" | while read -r line; do
                  echo "  Line $line"
                done
                MODIFIERS_FOUND=true
              fi
              
              # Check for .only with line numbers (exclude commented lines)
              ONLY_RESULTS=$(grep -n "\.only" "$file" | grep -v "^\s*//" || true)
              if [[ -n "$ONLY_RESULTS" ]]; then
                echo -e "\n⚠️ Found .only in $file:"
                echo "$ONLY_RESULTS" | while read -r line; do
                  echo "  Line $line"
                done
                MODIFIERS_FOUND=true
              fi

              # Check for commented .skip with line numbers (exclude this.skip())
              SKIP_RESULTS=$(grep -n "\.skip" "$file" | grep -v "this\.skip" || true)
              if [[ -n "$SKIP_RESULTS" ]]; then
                echo -e "\n⚠️ Found commented .skip in $file:"
                echo "$SKIP_RESULTS" | while read -r line; do
                  echo "  Line $line"
                done
                MODIFIERS_FOUND=true
              fi
              
              # Check for commented .only with line numbers 
              ONLY_RESULTS=$(grep -n "\.only" "$file" || true)
              if [[ -n "$ONLY_RESULTS" ]]; then
                echo -e "\n⚠️ Found commented .only in $file:"
                echo "$ONLY_RESULTS" | while read -r line; do
                  echo "  Line $line"
                done
                MODIFIERS_FOUND=true
              fi
            fi
          done
          
          # Show results and fail the job if modifiers found
          if [[ "$MODIFIERS_FOUND" == "true" ]]; then
            echo -e "\n📋 Modifiers found in the above files"
            echo "::error::Cypress code contains .skip or .only modifiers"
            echo "::error::Consider removing these before merging to main branch if applicable"
            # Fail the job to show red cross
            exit 1
          else
            echo "✅ No .skip or .only found in Cypress files"
            echo "::notice::No unwanted cypress modifiers were found"
          fi
        id: modifiers-check

      - name: No Cypress changes detected
        if: steps.changed-files.outputs.any_changed == 'false'
        run: |
          echo "ℹ️ No Cypress files were changed in this PR"
          echo "Skipping check"